CREATE TABLE IF NOT EXISTS users (
  id SERIAL4 PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS tasks (
	id SERIAL8 PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
  description TEXT,
  user_id INT4 NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
