CREATE TABLE IF NOT EXISTS users (
	id SERIAL4 PRIMARY KEY,
	password VARCHAR(128) NOT NULL,
	username VARCHAR(150) UNIQUE NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS tasks (
	id SERIAL8 PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description TEXT NOT NULL,
	user_id INT4 REFERENCES users(id)
);
